name: Maelstrom Tests

on: push

env:
  MAELSTROM_VERSION: "0.2.4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: make all

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: echo
            args: -w echo --bin ./bin/maelstrom-echo --node-count 1 --time-limit 10
          - name: unique-ids
            args: -w unique-ids --bin ./bin/maelstrom-unique-ids --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

    name: test-${{ matrix.name }}
    steps:
      - name: Install Maelstrom dependencies
        run: sudo apt-get install -y gnuplot graphviz

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache Maelstrom
        id: cache-maelstrom
        uses: actions/cache@v4
        with:
          path: maelstrom/
          key: maelstrom-${{ env.MAELSTROM_VERSION }}

      - name: Download Maelstrom
        if: steps.cache-maelstrom.outputs.cache-hit != 'true'
        run: |
          curl -L -o maelstrom.tar.bz2 \
            "https://github.com/jepsen-io/maelstrom/releases/download/v${MAELSTROM_VERSION}/maelstrom.tar.bz2"
          tar xjf maelstrom.tar.bz2

      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin/

      - run: chmod +x bin/*

      - name: Test
        run: ./maelstrom/maelstrom test ${{ matrix.args }}
